// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: humano.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Humano struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nombre        string                 `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Edad          int64                  `protobuf:"varint,2,opt,name=edad,proto3" json:"edad,omitempty"`
	Iq            int64                  `protobuf:"varint,3,opt,name=iq,proto3" json:"iq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Humano) Reset() {
	*x = Humano{}
	mi := &file_humano_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Humano) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Humano) ProtoMessage() {}

func (x *Humano) ProtoReflect() protoreflect.Message {
	mi := &file_humano_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Humano.ProtoReflect.Descriptor instead.
func (*Humano) Descriptor() ([]byte, []int) {
	return file_humano_proto_rawDescGZIP(), []int{0}
}

func (x *Humano) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Humano) GetEdad() int64 {
	if x != nil {
		return x.Edad
	}
	return 0
}

func (x *Humano) GetIq() int64 {
	if x != nil {
		return x.Iq
	}
	return 0
}

var File_humano_proto protoreflect.FileDescriptor

const file_humano_proto_rawDesc = "" +
	"\n" +
	"\fhumano.proto\x12\x04hola\"D\n" +
	"\x06Humano\x12\x16\n" +
	"\x06nombre\x18\x01 \x01(\tR\x06nombre\x12\x12\n" +
	"\x04edad\x18\x02 \x01(\x03R\x04edad\x12\x0e\n" +
	"\x02iq\x18\x03 \x01(\x03R\x02iqB\x06Z\x04./pbb\x06proto3"

var (
	file_humano_proto_rawDescOnce sync.Once
	file_humano_proto_rawDescData []byte
)

func file_humano_proto_rawDescGZIP() []byte {
	file_humano_proto_rawDescOnce.Do(func() {
		file_humano_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_humano_proto_rawDesc), len(file_humano_proto_rawDesc)))
	})
	return file_humano_proto_rawDescData
}

var file_humano_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_humano_proto_goTypes = []any{
	(*Humano)(nil), // 0: hola.Humano
}
var file_humano_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_humano_proto_init() }
func file_humano_proto_init() {
	if File_humano_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_humano_proto_rawDesc), len(file_humano_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_humano_proto_goTypes,
		DependencyIndexes: file_humano_proto_depIdxs,
		MessageInfos:      file_humano_proto_msgTypes,
	}.Build()
	File_humano_proto = out.File
	file_humano_proto_goTypes = nil
	file_humano_proto_depIdxs = nil
}
